// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chen.mm.domain;

import com.chen.mm.domain.Mission;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Mission_Roo_Configurable {
    
    declare @type: Mission: @Configurable;
    
}
